AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  order-shipments

  Order Shipments API

Globals:
  Function:
    Timeout: 25
    Environment:
      Variables:
        ENVIRONMENT: production
        EPCCURL: https://api.moltin.com

Parameters:
  ErrorEmailFromAddress:
    Description: 'Required.  The email address to use in the From section of error emails.'
    Type: 'String'
  ErrorEmailBccAddress:
    Description: 'Required.  The email address to use in the Bcc section of error emails.'
    Type: 'String'

Resources:
  GetOrderFulfillmentsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: order-shipments/
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Events:
        OrderShipmentsGet:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: get
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: jetti/EpJettiSecretKey
        - SSMParameterReadPolicy:
            ParameterName: jetti/*/EpccClientId
        - SSMParameterReadPolicy:
            ParameterName: jetti/*/EpccClientSecret

  PostFulfillmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/FulfillmentPostRequestProcessor.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          STATE_MACHINE_ARN:
            !Ref FulfillmentProcessorStepFunction
      Events:
        OrderShipmentsPost:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: post
      Policies:
        - StepFunctionsExecutionPolicy:
            StateMachineName:
              !Ref FulfillmentProcessorStepFunction

  FulfillmentProcessorStepFunction:
    Type: AWS::Serverless::StateMachine 
    Properties:
      DefinitionUri: statemachine/create-fulfillment.asl.json
      DefinitionSubstitutions:
        GetTokenFunctionArn:
          !GetAtt GetTokenFunction.Arn
        GetOrderFunctionArn:
          !GetAtt GetOrderFunction.Arn
        GetFulfillmentContainerFunctionArn:
          !GetAtt GetFulfillmentContainerFunction.Arn
        CreateFulfillmentFunctionArn:
          !GetAtt CreateFulfillmentFunction.Arn
        CreateFulfillmentItemFunctionArn:
          !GetAtt CreateFulfillmentItemFunction.Arn
        CreateFulfillmentItemRelationshipsFunctionArn:
          !GetAtt CreateFulfillmentItemRelationshipsFunction.Arn
        RollbackFulfillmentFunctionArn:
          !GetAtt RollbackFulfillmentFunction.Arn
        SendErrorEmailFunctionArn:
          !GetAtt SendErrorEmailFunction.Arn
      Policies:
        - LambdaInvokePolicy:
            FunctionName:
              !Ref GetTokenFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref GetOrderFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref GetFulfillmentContainerFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref CreateFulfillmentFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref CreateFulfillmentItemFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref CreateFulfillmentItemRelationshipsFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref RollbackFulfillmentFunction
        - LambdaInvokePolicy:
            FunctionName:
              !Ref SendErrorEmailFunction
  
  GetTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/GetToken.handler
      Runtime: nodejs12.x
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: jetti/EpJettiSecretKey
        - SSMParameterReadPolicy:
            ParameterName: jetti/*/EpccClientId
        - SSMParameterReadPolicy:
            ParameterName: jetti/*/EpccClientSecret

  GetOrderFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/GetOrder.handler
      Runtime: nodejs12.x

  GetFulfillmentContainerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/GetFulfillmentContainer.handler
      Runtime: nodejs12.x

  CreateFulfillmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/CreateFulfillment.handler
      Runtime: nodejs12.x

  CreateFulfillmentItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/CreateFulfillmentItem.handler
      Runtime: nodejs12.x

  CreateFulfillmentItemRelationshipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/CreateFulfillmentItemRelationships.handler
      Runtime: nodejs12.x


  CreateFulfillmentItemRelationshipsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/CreateFulfillmentItemRelationships.handler
      Runtime: nodejs12.x

  RollbackFulfillmentFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/RollbackFulfillment.handler
      Runtime: nodejs12.x

  SendErrorEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: order-shipments
      Handler: ./functions/SendErrorEmail.handler
      Runtime: nodejs12.x
      Environment:
        Variables:
          ERROR_EMAIL_FROM_ADDRESS: !Ref ErrorEmailFromAddress
          ERROR_EMAIL_BCC_ADDRESS: !Ref ErrorEmailBccAddress
      Policies:
        - SESCrudPolicy:
            IdentityName: "*"
        - SSMParameterReadPolicy:
            ParameterName: jetti/*/ErrorEmailRecipient

Outputs:
  FulfillmentProcessorStepFunctionArn:
    Description: "Step function to process a POST request of a Jetti fulfillment"
    Value: !Sub FulfillmentProcessorStepFunction.Arn
  FulfillmentsApi:
    Description: "Fulfillments Lambda Function API URL"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/order-fulfillments/"
